services:
  api:
    deploy:
      resources:
        limits:
          cpus: "2"
    command:
      - uv
      - run
      - --no-dev
      - uvicorn
      - src.entrypoint.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --workers
      - "2"
